### ISSUE TITLE
New `libe_specs` for saving history file

### ISSUE THREAD

**Issue by AngelFP** [Libensemble/libensemble#1103]
There are a couple of features that would be very useful regarding how the history is saved.

1. Saving the history file when the run is completed. Currently it is saved every `k_sims` or `k_gens`, but the last few iterations are missing if, for example, `sim_max` is not a multiple of `k_sims`. This could be implemented by forcing a save on [_final_receive_and_kill](https://github.com/Libensemble/libensemble/blob/52e45af00b217c39f107b2ca5354d7dfdfdff256/libensemble/manager.py#L517). Currently, a workaround is to use this [function](https://github.com/Libensemble/libensemble/blob/52e45af00b217c39f107b2ca5354d7dfdfdff256/libensemble/tools/tools.py#L79C8-L79C8) from the tools, but the name of the file follows a different format and leads to always having 2 history files per run (plus a .picke file).
2. Choose whether the date information should be added to the name of the history file. Having this enabled by default results in many history files being created in optimas when a single exploration is run in several steps or resumed (https://github.com/optimas-org/optimas/pull/118). This is because the `_save_every_k` method is not able to delete the old files, which were created in previous calls to `libE`.
3. As a "nice to have", it would be convenient to have some control on the name of the history file.

Below is an example of how these options could be controlled by the user.
 
```python
libe_specs['save_history_on_completion'] = True
libe_specs['save_history_with_date'] = False   # To save as `libE_history_after_sim_{}.npy`
libe_specs['history_file_prefix'] = 'exploration_history'  # Would allow us to customize it to  `exploration_history_after_sim_{}.npy` in optimas.
```

Let me know what you think.

**Comment by jlnav** [comment]
Hey @AngelFP !

We got around to internally discussing the defaults in #1141 . Just noting here we decided the following:

- `save_H_on_completion` will be False by default, but if a `_save_every_k` option is also set, will be flipped on to True.
- persis_info will also be dumped when save_H_on_completion is set.

**Comment by AngelFP** [comment]
Hi @jlnav, thanks for the update. The first one looks like a good default to me. With respect to the second point, I'm not sure. The setting says `save_H`, so the fact that it also saves persis_info might not be clear to the user. For the particular case of optimas, we don't need the persis_info file, so I would in principle avoid saving it to simplify the output.

Just being a bit nitpicky, it's great to have these options already :D
