### ISSUE TITLE
Duplicate code in regression tests

### ISSUE THREAD

**Issue by jmlarson1** [Libensemble/libensemble#121]
Many of our regression tests are epsilon different from each other. For example, we want to make sure that nlopt, scipy, and petsc4py local optimizers all work within APOSMM. Currently, we use three different scripts to test each. This results in a lot of duplicate code. (Perhaps a different sim_func or alloc_func is used/tested.) 

I can see some different possibilities:

1. Keep different files 
 - **Pluses:** Allows easy sharing with others. Example scripts are just regression tests. Can easily identify issues when a regression test failed.
 - **Minuses:** Lots of duplicate code (and it's going to get worse as we add features). 
2. Combine similar regression tests into single file and then loop over different functionality
 - **Pluses:** Less duplicate code. Possibly better organized (would all APOSMM tests be in one file?)
 - **Minuses:** Harder to debug (which loop caused the failure?). Harder to share specific examples (but not terribly hard). Requires being much clearer inside loop about which features are being tested. 
3. Use helper functions. 
 - **Pluses:** Less duplicate code. 
 - **Minuses:** More confusing structure as many regression tests would load common files and then slightly modify them for a given test. More difficult to share examples.

**Comment by shuds13** [comment]
I'm inclined towards 3 and keep each test end-to-end, though I'm not sure why we need to modify common files?

**Comment by dbindel** [comment]
I also am inclined toward 3.  The problem with 2 is that we then make it so that (for example) testing APOSMM with NLOpt will still require running a file that loads the petsc4py local optimizers, which causes problems if we want to run with multiprocessing as the comm (for example).

Cheers,
David

**Comment by shuds13** [comment]
There is a point, though, that we consider these as user examples, I already thought this a bit, with the use of common.py. Maybe we should have selected examples that are standalone for the examples dir.

**Comment by jmlarson1** [comment]
I updated this issue to clarify that we are not modifying the files. Having all regression tests be examples may be redundant. I'll take a branch off master and see what happens when implementing 3.

**Comment by jmlarson1** [comment]
We ultimately kept some duplicate code so that the regression tests were able to be used as examples. Some common code was moved to 
    `/libensemble/libensemble/tests/regression_tests/common.py`
and 
    `/libensemble/libensemble/tests/regression_tests/support.py`
