### ISSUE TITLE
Regression tests that quit should not report as having completed.

### ISSUE THREAD

**Issue by jmlarson1** [Libensemble/libensemble#129]
For understandable reasons, some regression tests do not run with all launchers. For example, 

`test_chwirut_uniform_sampling_one_residual_at_a_time.py `

has the following code:
````
if libE_specs['comms'] != 'mpi':
    quit()
````
Yet, the testing script reports 

````
 ---Test 75: test_chwirut_uniform_sampling_one_residual_at_a_time.py using local on 2 processes  ...passed 
 ---Test 76: test_chwirut_uniform_sampling_one_residual_at_a_time.py using local on 4 processes  ...passed 
 ---Test 77: test_chwirut_uniform_sampling_one_residual_at_a_time.py using tcp on 2 processes  ...passed 
 ---Test 78: test_chwirut_uniform_sampling_one_residual_at_a_time.py using tcp on 4 processes  ...passed 
````

Should `run_tests.sh` check a 0-1 array (where rows correspond to tests and columns correspond to different launchers) and only run tests/launchers with a 1?

**Comment by shuds13** [comment]
Each regression tests contains comment lines of the following format:

# TESTSUITE_COMMS: mpi local tcp
# TESTSUITE_NPROCS: 2 4

run-tests.sh reads and parses these to determine which comms and number of processors to run that particular test.
