### ISSUE TITLE
Review sim function one_d_example (possible bug).

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#1352]
What is the idea of this sim function that does not extract the `x` field from the numpy structured array. If extended to 2D it does not work, but only operates on the first dimension.

Also, the docstring says "Evaluates the six hump camel function for a single point ``x``"

It is not using six hunp camel, and is not just working for single point, but single dimension.

Perhaps `x = H["x"]` is required. I suggest we make this work with >1D, though maybe on a single point still.

It is also used in examples in docs such as in the `ensemble.py` docstring.

A duplicate is also used in functionality test `test_1d_super_simple.py`

**Comment by jmlarson1** [comment]
If we are discussing,
https://github.com/Libensemble/libensemble/blob/main/libensemble/sim_funcs/one_d_func.py
then, yes, I would think we would need `x = H["x"]`, unless this taken care of in the
`@input_fields(["x"])`
decorator. Perhaps @jlnav knows that?

**Comment by jmlarson1** [comment]
I am not sure what the `d` in the name is referring to. It's a very general sim_f. Certainly the docstring is incorrect. 

A name such as "simple_sim" or "norm_eval" seem much more appropriate.
