### ISSUE TITLE
Pydantic warnings

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#1404]
Tests in CI showing a lot of pydantic warnings such as:

/home/runner/miniconda3/envs/condaenv/lib/python3.9/site-packages/pydantic/_internal/_config.py:322: UserWarning: Valid config keys have changed in V2:
* 'orm_mode' has been renamed to 'from_attributes'
  warnings.warn(message, UserWarning)

See https://github.com/Libensemble/libensemble/actions/runs/10393072943/job/28779738691

**Comment by jlnav** [comment]
Closed by #1410
