### ISSUE TITLE
MPIExecutor wait_time always set by wait_on_start

### ISSUE THREAD

**Issue by cchall** [Libensemble/libensemble#1468]
The change to the `wait_on_start` feature of the MPIExecutor in 1ba9f5721bcd7794b7a8c0ac6dfc81516c9f6c03 to change it from bool to either bool or int  looks like it results in MPIExecutor.fail_time always being ignored. 

In the case `wait_on_start=True` it looks like MPIExecutor.fail_time should be used to set the wait time. However, the check https://github.com/Libensemble/libensemble/blob/2892c864cc0a0d01e9ad6424d218b44ef2433640/libensemble/executors/mpi_executor.py#L169
always passes with the first condition because bool is a subclass of int. This can cause failed simulations to not be caught if fail_time > 1 was needed.

**Comment by jlnav** [comment]
Thanks Chris for the bug report! The corresponding fix should appear in our upcoming release.
