### ISSUE TITLE
test_comms.py with TCP fails

### ISSUE THREAD

**Issue by jmlarson1** [Libensemble/libensemble#158]
With TCP and 4 workers, `H['sim_worker']` does not match the `H['arr_vals']`, even though the `sim_f` assigns `arr_vals` to be `jobctl.workerID` (times a constant). 

Is the `workerID` reported from `JobController` different form the `sim_worker` passed to the `update_history_x_out` function in `/libensemble/history.py`?

**Comment by shuds13** [comment]
It looks like on TCP comms there may be a difference between workerID entered into H and what the worker receives as its ID. Suggest we consult @dbindel on the intention here.

I have created another sim_func for the test_comms which transforms the x input,  and that one seems to work.

**Comment by shuds13** [comment]
Treating as two different identifiers. Removing workerID test and replace with the x transformation test
