### ISSUE TITLE
Cannot obtain SMT information from LSF environment on Summit

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#159]

**Comment by shuds13** [comment]
Under LSF the environment variable LSB_HOSTS is used to obtain lists of cores per node as well as number of available nodes for auto_resources. However, there does not seem to be environment information to obtain the number of available SMT threads, and so the logical core count is returned the same as the physical core count.

**Comment by jlnav** [comment]
Resolved via platform support/enhancements
