### ISSUE TITLE
Achieve xSDK compliance

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#208]
Make modifcations to enable xSDK compliance.
- [x] Remove output to stdout/stderr
- [x] Create files CHANGELOG AND SUPPORT at top level
- [x] Remove direct use of MPI_COMM_WORLD (except for default if not passed)
- [x] Create function in setup.py to return list of dependent packages.

**Comment by jlnav** [comment]
I suggest related branches have a 'xsdk' tag. For example, 'xsdk/add-support'
