### ISSUE TITLE
OpenMPI does not work correctly with direct launches

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#22]
OpenMPI does not work correctly with direct launches. It is not clear whether OpenMPI should support a nested mpiexec structure.  This should not affect execution with a proxy job launcher, such as Balsam. This should also be tested.

**Comment by shuds13** [comment]
OpenMPI does not officially support nested mpiexecs. So to run with OpenMPI, we will need to use a proxy launching system.

**Comment by jmlarson1** [comment]
Does Balsam resolve this issue?
