### ISSUE TITLE
Build with Spack, including all options, on Theta, Summit and Cori

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#231]
Build libEnsemble with Spack, including all dependency options, on Theta, Summit and Cori, and provide instructions. The options will include MPI, PETSc, NLopt and SciPy.

This supports xSDK testing and potentially provides an all-in-one solution for a pre-built libEnsemble
software stack, optimized to each platform, which can be provided through a module.

**Comment by jmlarson1** [comment]
Have we been able to do spack-builds on these systems?

**Comment by shuds13** [comment]
We have Spack builds on all systems, but we don't quite meet this for all options. NLopt did not build with Python, for example. Other issues are on the libe_spack kanban.
https://github.com/Libensemble/spack_libe/projects/1

**Comment by wildsm** [comment]
This platform has been migrated to XSDK build and CI.
