### ISSUE TITLE
Investigate and fix the NumPy FutureWarnings in unit test output

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#234]
Investigate and fix the NumPy FutureWarnings in unit test output (see travis output):

 eg. FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. See for example: https://travis-ci.org/Libensemble/libensemble/jobs/573953543

**Comment by jlnav** [comment]
Closed by #239
