### ISSUE TITLE
Assess nprocesses as libE_specs field name

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#235]
'nprocesses' [int]:
        Number of worker processes to spawn (in local/tcp modes)

I propose this would be better named nworkers, as it would seem less ambiguous, unless there is a counter-argument.

**Comment by jlnav** [comment]
This change makes sense, and would improve lines like:

`libE_specs = {'nprocesses': nworkers, 'comms': 'local'}` in `common.py` and `nworkers = libE_specs['nprocesses']` in `libE.py`.

Also, when using `parse_args()` manually, `nprocesses` is specified as `--nworkers #` anyway.
