### ISSUE TITLE
Port QuickPIC to use jobcontroller

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#236]
Implement job controller interface for QuickPIC example and test on multiple platforms including Bebop.

**Comment by jlnav** [comment]
Status update:

A QuickPIC/libEnsemble example implementing the job controller has been developed and tested on 1, 4, and 8 Broadwell nodes on Bebop.

Todos:

- [ ] Test larger scales, timeframes, other architectures on Bebop

- [ ] Test on Theta, etc. (?)

**Comment by jlnav** [comment]
Closing until future work with libEnsemble can continue
