### ISSUE TITLE
Code run with the --local communicator isn't included in coverage

### ISSUE THREAD

**Issue by jmlarson1** [Libensemble/libensemble#245]
See, https://coveralls.io/jobs/53144464/source_files/395971636

**Comment by jlnav** [comment]
With `--concurrency=multiprocessing` specified on `COV_LINE_PARALLEL`, the only other command-line option is `--parallel-mode`,  which is also specified in `/regression_tests/.coveragerc`. So "all options" may already be covered by the configuration files.

**Comment by jlnav** [comment]
`local` coverage is being tracked, but `tcp` coverage needs further investigation.
