### ISSUE TITLE
[Errno 17] File exists: 'libopenblasp-r0.3.6.so' - Travis

### ISSUE THREAD

**Issue by jlnav** [Libensemble/libensemble#255]
[Travis] Python 3.5 builds for new branches or pull requests often fail with the error:

`[Errno 17] File exists: 'libopenblasp-r0.3.6.so' -> '/home/travis/miniconda/envs/condaenv/lib/libcblas.so'`

This error typically disappears on future pushes or after restarting the build.

**Comment by jmlarson1** [comment]
I've seen this error frequently. 

Note that there haven't been any commits to the (core) cpython 3.5 branch in almost a month:
https://github.com/python/cpython/branches/all
 
According to this table, 3.5 is only receiving security fixes:
https://devguide.python.org/#status-of-python-branches

It's annoying to have to keep restarting travis builds.

**Comment by jlnav** [comment]
I don't think this error has reappeared since the #259 merge. If it happens again, I will reopen this issue.
