### ISSUE TITLE
Consider restructuring sim and gen directory creation

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#267]
The following applies both to sim and gen.

Currently, a directory sim_worker_<worker_id> (or gen_worker_<worker_id>) is created for each each worker, each copying the contents of a specified sim (or gen) input directory. For each point (or each sim call) evaluated by the worker, the contents of this directory is either overwritten, or the user is responsible, via their sim func, to create sub-directories in which to run each job - involving a second copy of input data (or possibly a sim link). This does allow the user to name the directory as they wish.

Also, the separate worker directories can potentially live on distributed storage resources (e.g. on-node SDD). And input data copied to the worker directory can be re-used between sim calls.

Note, that in some cases there is a sim and gen worker directory for the same worker.

This two step process may place an unnecessary burden on the user to set up their own simulation sub-directories in the sim func, and in cases where local storage resources are not used, the separate worker directories may not be needed.

A more intuitive approach may be to focus on copying/referencing the input data for each point in H, or each sim (or gen) call, rather than for each worker. Many users may not require to name each directory, and a random hash could be used. libensemble can then place the user and run the sim func  inside that directory. Also, the worker directories could be optional, and would just be worker1/worker2..

A downside of this approach may be reduced flexibility. If the user does want to name their own directories inside the sim func. Or if they want to store shared input in the worker level directory. Provisions could be made for these options while having a simpler default. The job_controller (as currently named) could also help with a jobctl.create_workdir(name) function once a directory name is created in the user sim func. This function could also potentially take other options for data copying/referencing.

**Comment by jlnav** [comment]
Moving some comments and progress to Issue from Pull Request.

TODO:

- [ ] Per-calculation directories differentiated with sim IDs instead. Or, spec to allow user to choose.

- [ ] Per-calculation directories created by default, but can be disabled

- [ ] Rename specs options: 'sim_dir' -> 'input_dir', 'sim_dir_prefix' -> 'ensemble_dir_path', etc.

- [ ] Setting for user to list which files to symlink, which to copy.

- [ ] Worker-directories don't need input_dir prefix, only worker-number.

**Comment by jlnav** [comment]
Tentatively closed by #334
