### ISSUE TITLE
Consolidation of libE_specs

### ISSUE THREAD

**Issue by jmlarson1** [Libensemble/libensemble#272]
Currently, libE uses `sim_specs` for much of what should be a general `libE_specs` field. For example, 
- `sim_specs['profile']` profiles a worker, but not explicitly the simulation evaluations. 
- `save_every_k` is a libE manager operation, and nothing is done by the worker, let alone `sim_f`. Therefore `save_every_k_sims` should be in `libE_specs`

**Comment by jmlarson1** [comment]
Addressed by PR #273

**Comment by jlnav** [comment]
Presumably closed by #273
