### ISSUE TITLE
UnpicklingError

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#28]
libEnsemble gets the following Intermittent error on the comm.recv:

_pickle.UnpicklingError: invalid load key, '\x00'.

on Bebop Cray CS400 on knl nodes.

causing the run to abort.

**Comment by shuds13** [comment]
This seems to be occur mainly on the OFA fabric. The current workaround is to run on the TMI fabric with matching probes disabled.

export I_MPI_FABRICS=tmi

(export I_MPI_FABRICS=shm:tmi can be used,  but usually shm for intranode comms is default behaviour for this system).

(this should be the default, with standard environment)

At top of script calling script (above any other imports of mpi4py do):

import mpi4py
mpi4py.rc.recv_mprobe = False

A more detailed analysis is given at:

https://bitbucket.org/mpi4py/mpi4py/issues/102/unpicklingerror-on-commrecv-after-iprobe

**Comment by shuds13** [comment]
We are now avoiding this by not using the OFA fabric. The error does not occur on TMI

**Comment by shuds13** [comment]
As this issue has been reported and acknowledged to be an issue running with OFA, the current approach is to avoid the OFA fabric. I will try running again with current software stack and see if this issue still occurs.

**Comment by jmlarson1** [comment]
Can we mark this issue as closed?

**Comment by jlnav** [comment]
Tentatively closed due to each of our example batch submission scripts accounting for this issue. This can be reopened when it's investigated further
