### ISSUE TITLE
Improved timing is needed

### ISSUE THREAD

**Issue by jmlarson1** [Libensemble/libensemble#318]
libEnsemble currently uses the python `time` module for timing. We should use `datetime` if we want to ensure sub-second accuracy (which we do):

For example, see the discussion here:
https://stackoverflow.com/questions/5998245/get-current-time-in-milliseconds-in-python

I think the most pressing place to address this is 

`/libensemble/util/timer.py`

but looking at the many files returned from running: 

`grep -r --include=*.py "import time"`

in the base libEnsemble directory shows how widespread this use is. 

(I'm unsure whether this is the source of intermittent timing tests that fail on Travis.)

**Comment by jlnav** [comment]
Was this sufficiently addressed by #320 ? What other features or improvements are needed?

**Comment by jmlarson1** [comment]
I think #320 is sufficient.
