### ISSUE TITLE
Review alloc_specs defaults

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#325]
Is the defaulting alloc_specs in the libE function definition the best way. The issue is that if someone has been using defaults and then wants to change something they have to copy whats there into alloc_specs first. Would it be better/feasible to default the different aspects at a lower level. E.g. The 'user' field defaults (batch_mod and num_active_gens) might be defaults in the alloc funcs themselves. Not sure if allocated should always be used? The default alloc_func could be set as an individual field if that field does not exist (inside libE).

Then they could just say e.g.:
alloc_specs['user']['batch_mode']=True

and pass to libE.

The current approach may have the benefit that its clear from the function definition. https://libensemble.readthedocs.io/en/develop/libe_module.html
and when it is user specified its complete.

A third way might be a util function eg.
alloc_specs=util.get_alloc_defaults()

which could then be modified.

Is there a preference to stick to the current approach or change? Or maybe stick with the alloc_func default as now but put the user defaults into the alloc funcs?

**Comment by jmlarson1** [comment]
My preference would be to change it from how it is. It doesn't have to be declared at the highest level (at the `libE` call).

**Comment by jlnav** [comment]
Tentatively closed by #342
