### ISSUE TITLE
Manager to handle failed worker calculations

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#34]
Manager needs to take action based on returned calc_status which could include worker exceptions that have been caught. This may, for example, include re-issuing points for evaluation.

**Comment by shuds13** [comment]
Note,  There currently exists some code in Manager/Worker to handle communication errors. This includes requesting a message re-send, and request a pickle dump of message. This is not tested in testsuite currently and has not been used with persistent workers. This should be formalised.

**Comment by wildsm** [comment]
Will address if there is a user who wants to do this.
