### ISSUE TITLE
ReadTheDocs is using too much memory

### ISSUE THREAD

**Issue by jmlarson1** [Libensemble/libensemble#354]
- Our readthedocs builds are [failing](https://readthedocs.org/projects/libensemble/builds/10439412/).

- This came after adding additional dependencies to our regression tests (tasmanian, DFOLS, etc). 

- We don't need those dependencies when building our documentation. 

- How do we specify the dependencies used in `.readthedocs.yml` as suggested [here](https://docs.readthedocs.io/en/stable/guides/build-using-too-many-resources.html#reduce-documentation-build-dependencies).

- I see [here](https://docs.readthedocs.io/en/stable/config-file/v2.html#migrating-from-v1) that the preferred way to state requirements is with `python.install` but the warning [here](https://docs.readthedocs.io/en/stable/config-file/v2.html#python-system-packages) says that our `conda` argument takes precedent. 

- Is there a way to remove large packages from our `conda` [environment](https://docs.readthedocs.io/en/stable/config-file/v2.html#conda-environment) so they aren't built?

**Comment by jmlarson1** [comment]
This issue was transient, but the underlying issue may need to be addressed in the future. Closing for now.

**Comment by jmlarson1** [comment]
Maybe not as transient as I thought:
https://readthedocs.org/projects/libensemble/builds/10441298/

(I even tried a fresh RTD wipe)

**Comment by shuds13** [comment]
It looks like its failing just creating the conda environment from environment.yml. All we have there is:

channels:
  - conda-forge
  - defaults

dependencies:
 - sphinxcontrib-bibtex
 - python>=3.6

I don't think its even got as far as installing the new dependencies. I suggest raising a readthedocs issue. This should not be a problem unless sphinxcontrib-bibtex is huge!!!

**Comment by jmlarson1** [comment]
Well sphinxcontrib-bibtex built before... so I'm not sure what's happening. 

It looks like a similar issue has been opened here:
https://github.com/readthedocs/readthedocs.org/issues/6664

@jlnav can open an issue and point to the tensorflow issue?

**Comment by jmlarson1** [comment]
I also see other similar issues:

https://github.com/readthedocs/readthedocs.org/issues/6627

and 

https://github.com/readthedocs/readthedocs.org/issues/6647

Perhaps RTD started enforcing stricter requirements, or they have a new issue.

**Comment by jlnav** [comment]
I'm reading those threads and researching some of the suggestions here: https://docs.readthedocs.io/en/stable/guides/build-using-too-many-resources.html

Am I right in my understanding that the only **docs** dependency is `spinxcontrib-bibtex`? One of the listed suggestions is use ``pip`` instead of ``conda`` since Conda may have memory consumption issues.

**Comment by shuds13** [comment]
The are more dependencies bought in, I think from conf.py specifications, but these happen in a future step - eg. https://readthedocs.org/projects/libensemble/builds/10454726/
(see the following step).

It looks like we tried pip before - I don't recall what was the result:
https://github.com/readthedocs/readthedocs.org/issues/6364#issuecomment-555106215

but you could try:

dependencies:
 - python>=3.6
 - pip:
   - sphinxcontrib-bibtex

**Comment by jmlarson1** [comment]
Addressed by PR #356
