### ISSUE TITLE
Fix "ModuleNotFoundError: No module named 'more_itertools'" on develop

### ISSUE THREAD

**Issue by jlnav** [Libensemble/libensemble#374]
Turns out this module isn't actually built-in.

**Comment by jmlarson1** [comment]
Just add it to the `pip install` on Travis?

**Comment by jlnav** [comment]
> Just add it to the `pip install` on Travis?

It's a dependency installed by pytest on Travis, so it's absence hasn't been causing issues there. It's absent on Bebop, which is causing issues. I'd like to see if I can replicate what the single function I use from more-itertools accomplishes so we can avoid an extra dependency.

**Comment by jmlarson1** [comment]
> can avoid an extra dependency.

See the built-in option here:
https://stackoverflow.com/questions/2154249/identify-groups-of-continuous-numbers-in-a-list

**Comment by jlnav** [comment]
Closed by #379
