### ISSUE TITLE
Check sim['in'] are in gen['out']

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#382]
I propose check_inputs() should check that if a gen exists, then anything in sim['in'] is defined in gen['out].

Are there possible exceptions to this?

**Comment by jmlarson1** [comment]
I can think of cases where everything into the sim is not in `gen_specs['out']`. Perhaps resources to be used is an `alloc_spec['out']`. Perhaps the some filename or mesh information is computed beforehand and given in `H0`. Is it enough to do a check that everything in `sim_spec['in']` is a key in `H` (after it has been created)?

**Comment by jmlarson1** [comment]
Addressed by #395
