### ISSUE TITLE
Implement subprocess/multiprocess launches of calc funcs by workers.

### ISSUE THREAD

**Issue by jlnav** [Libensemble/libensemble#388]
Longer term goal. Add more details below.

**Comment by shuds13** [comment]
Consider subprocessing calc from worker.

For:
- Worker kills long running calc by default; without user catch (The signal could be caught for user control over shutdown).
- Worker could get/send data to/from persis calcs (persis calc has to still interact with worker). This would require a communicable sub-process (e.g. multiprocessing)
- Benefit if libE exit requires handshake with workers. Consider #387.

Against
- Some overhead (including an extra process/hw thead for every worker (consider node limitations - esp on launch nodes).
- User control over receiving manager signal and checkpoint/controlled shutdown would need to change.
- Multiple nesting of processes - possible contention/complexity *.

*e.g.
- mpi4py or tcp or multiprocessing comm
   - multiprocessing between worker and calc
      - multiprocessing within calc(eg. APOSMM)
