### ISSUE TITLE
Worker Exceptions hanging on Bebop

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#389]
Some Opal runs are hanging on worker exceptions. The exceptions (in user sim funcs) should be caught and send back to the manager, prompting an abort. The exceptions are not being sent back.

It seems this is something recent in as this has been tested extensively on Bebop in the past. The user is working off the develop branch.

**Comment by jmlarson1** [comment]
Does `master` not present the issue?

**Comment by shuds13** [comment]
I will have to double check that. I'll re-word slightly.

**Comment by shuds13** [comment]
This turned out to be caused by an imported library in the user sim func that uses the logging.config.dictConfig function to initiate it's own logging from a yaml file. This function disables all existing loggers by default (https://docs.python.org/3/library/logging.config.html) - apparently for backward compatibilty! As exceptions are returned to the manager via the logger, nothing was being received as the libEnsemble loggers had been deleted.

I have recommended to the given library, that this can be changed by adding the `disable_existing_loggers: false` option.

I don't think there is really a libEnsemble side fix to this, given how Python logging works. There is always a full list of loggers available at the root level.
