### ISSUE TITLE
Persistent gen with an assertion error hangs

### ISSUE THREAD

**Issue by jmlarson1** [Libensemble/libensemble#398]
See the modification to `/regression_tests/test_persistent_aposmm_dfols.py` on the branch:

`debugging/hanging_persis`

**Comment by jlnav** [comment]
For starters, from a few quick experiments it appears other un/intentional errors within local optimization run processes also cause hangs. The LocalOptInterfacer can't conclude until it receives a response from it's process, correct?

**Comment by shuds13** [comment]
Yes, I will look for the best way. One approach would be to try/catch exceptions in your optimizer and in the except, send a message to the parent aposmm, which could then join the processes and raise the error. I will check if there is a more direct way.

**Comment by shuds13** [comment]
I have put of test of the above solution on the branch debugging/hanging_persis

I just did for dfols, see if this works for  you. If so I will generalise it.

**Comment by jmlarson1** [comment]
I think that will work. I'm not sure what all needs to be set other than `parent_can_read` after the exception. Does `child_can_read` need to be adjusted?

Is it possible to have the try/catch outside of the individual local optimization calls, or would that require adjusting `multiprocessing.Process`?

Overall, this looks reasonable. Thanks.

**Comment by shuds13** [comment]
So far I just did what was needed to raise the error. I did not shut down the child processes. I should probably do that, which will require some extra lines. They will be killed when the parent is killed, but as the top process currently is the worker process if the error is handled higher up they could be left going. 

It would be good if we could put try/catch outside, but it has to be in the subprocess, so I think that would mean adding a wrapper.

**Comment by jmlarson1** [comment]
I agree that it doesn't look possible having it outside of the subprocess.

**Comment by shuds13** [comment]
I will add a wrapper function - it can pass run_local_opt as an arg.

**Comment by jlnav** [comment]
If I understand this right, the new Process() target will be the wrapper function, containing the local_opt routine and surrounding error-handling?

**Comment by shuds13** [comment]
Correct

**Comment by shuds13** [comment]
I have pushed the wrapper approach. 

If we rearranged the args, then opt_runner could peel off what it needs and pass *args. But this is not a big deal.

**Comment by jmlarson1** [comment]
This was resolved by #465
