### ISSUE TITLE
Create a comms module/class

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#42]
The communications (mpi4py) routines should all be in a comms module. This is important to allow for examination of different types of worker concurrency. If also, allows for easier experiementation with the communication, and cleaner testing (a mocking comms class could possibly be built in). The intention is to use a base class comms, which can be inherited by various classes.

**Comment by jmlarson1** [comment]
David Bindel might be able to comment on this. POAP uses mocking.

**Comment by shuds13** [comment]
Created, Tested, Released (v0.5.0)

mpi4py, multiprocessing and TCP comms supported as of v0.5.0
