### ISSUE TITLE
Make a History Class

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#44]
It may be useful to convert the history array into a Class. This will include the attributes of the array itself, and relevant indexing attributes. Routines to update would be moved from manager.

A key question would be the user interface to alloc_f/queue_update_function routines which are currently passed sub-arrays.

**Comment by shuds13** [comment]
Created a feature/history_class branch.

This is implemented. Currently the history object is passed to  alloc_f/queue_update_function. This needs review.

**Comment by jmlarson1** [comment]
@shuds13 Can we close this issue?

**Comment by shuds13** [comment]
Yes, History class has been created and merged to master. Unit testing 100%.
