### ISSUE TITLE
deap expects fitness values as list

### ISSUE THREAD

**Issue by nneveu** [Libensemble/libensemble#442]
On branch `develop`, line 75 of the [deap persistent gen](https://github.com/Libensemble/libensemble/blob/develop/libensemble/gen_funcs/persistent_deap_nsga2.py) breaks if fitness values are returned in an array from the sim func. The deap toolbox is expecting a list. 

I fixed this in my local copy by forcing the array to be a list: 

`ind.fitness.values = list(calc_in['fitness_values'][i])`

(Sorry for introducing this bug in the first place)

**Comment by jmlarson1** [comment]
This was addressed by #474
