### ISSUE TITLE
APOSMM Tutorial

### ISSUE THREAD

**Issue by jlnav** [Libensemble/libensemble#468]
Draft an additional tutorial introducing APOSMM with libEnsemble.

Material from https://libensemble.readthedocs.io/en/master/examples/aposmm.html can serve as a good starting point.

Should this tutorial just be applied to six_hump_camel? Maybe start off with 6hc, then tie into using with Forces from previous tutorial.

**Comment by jmlarson1** [comment]
@jlnav I agree with starting with six_hump_camel for now. In this tutorial, it would be nice to show plots of the progress of APOSMM to the various minima. Can you make a post-proc script or plotting script that can plot the contours of the six_hump_camel function (or any 2D function) over the given domain?

**Comment by jlnav** [comment]
Closed by #472 , adjustments in progress.
