### ISSUE TITLE
Ensure all test dependencies in setup.py

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#479]
Ensure all test dependencies in setup.py such as Octave.

Also decide and take action on whether to create a simpler set of tests that users can run. For example, without Balsam/Octave/Tasmanian..

**Comment by jlnav** [comment]
I think this has been satisfied by #654 , since the default ``run-tests`` without extra flags doesn't include tests with Balsam/Octave/Tasmanian etc. I don't think we need to add those dependencies to ``setup.py`` with those tests primarily being covered by CI
