### ISSUE TITLE
"Best Practices" or Writers Guide for User Functions

### ISSUE THREAD

**Issue by jlnav** [Libensemble/libensemble#485]
In documentation hierarchy: User Guide -> Programming with libEnsemble -> (new) User Function Writers Guide

Details:
- flake8 or other standards for inclusion in libEnsemble (if requested)
- Standards for documenting user function
- Describe separation of calculation and parsing of libE data structures (e.g. six_hump_camel)
- etc.

[more ideas please]

**Comment by jmlarson1** [comment]
Guides for building regression/unit tests for new user functions.

**Comment by jlnav** [comment]
Tentatively closed by #510
