### ISSUE TITLE
petsc4py dfols missing modules

### ISSUE THREAD

**Issue by LDAmorim** [Libensemble/libensemble#487]
Hi all,
Sorry to bother you.
I am Diana and I work with [WarpX](https://github.com/ECP-WarpX/WarpX).

In these past days I have been trying to use it with libEnsemble on the OLCF Summit computer cluster.
I am new to using libEnsemble so I have been trying to follow the instructions in our repo's libEnsemble documentation and I got a bit stuck at a segfault.

Then I decided to follow your documentation for [Summit](https://libensemble.readthedocs.io/en/master/platforms/summit.html) and I encountered some basic issues that I can fix, but wanted to ask you if they exist because I am doing something wrong.

I thought that from the running script and the file [requirements.txt](https://github.com/Libensemble/libensemble/blob/master/libensemble/tests/scaling_tests/warpx/requirements.txt) I could understand all required required packages, so my initial installation was:
```bash
module load python
conda create --name LDA_conda python=3.7
export PYTHONNOUSERSITE=1
source activate LDA_conda
module load gcc
module load cuda
CC=mpicc MPICC=mpicc pip install mpi4py --no-binary mpi4py
pip install libensemble
conda install -n LDA_conda -c conda-forge matplotlib
conda install -n LDA_conda -c conda-forge numpy
conda install -n LDA_conda -c conda-forge scipy
conda install -n LDA_conda -c conda-forge yt
conda install -n LDA_conda -c conda-forge nlopt
conda deactivate
```

And after I got the error messages that the modules `petsc4py` and `dfols` were missing, I added:
```bash
conda install -n LDA_conda -c conda-forge petsc4py
pip install DFO-LS
```

Then I get the error of not finding the plotting files mentioned at the end of [summit_submit_mproc.sh](https://github.com/Libensemble/libensemble/blob/develop/libensemble/tests/scaling_tests/warpx/summit_submit_mproc.sh). So I changed the line `export LIBE_PLOTS=true` to `false`.

And now it seems to me that everything runs well.

Thank you for your work and the very clear documentation!
Cheers,
Diana

**Comment by jmlarson1** [comment]
Thank you very much for bringing this up. 

`pestc4py` and `dfols` aren't requirements, but they are used in some of the tests/examples. What script were you trying to run when the error message was raised?

**Comment by LDAmorim** [comment]
Thank you for the super quick reply @jmlarson1 !
I was trying to run the example in: https://github.com/Libensemble/libensemble/tree/develop/libensemble/tests/scaling_tests/warpx

**Comment by shuds13** [comment]
As long as you have the lines:

    import libensemble.gen_funcs
    libensemble.gen_funcs.rc.aposmm_optimizers = 'nlopt'

before importing aposmm, then it should not complain about missing dfols/petsc. 

You will need those to run the libensemble testsuite, however.

We should probably default plot scripts to false, I will change that. BTW, those scripts can be found in the postproc_scripts directory in libensemble.

Also, you will wan't to make sure the version you are using has [this fix](https://github.com/Libensemble/libensemble/commit/51103e7e48a2aa4077a857c67a3b1a34982d263f#diff-325e8605cfc614efe4178ef2831fff32). Perhaps this was the original issue.

**Comment by LDAmorim** [comment]
Thank you @shuds13 , yes that fixed the problem of dfols/petsc, sorry I didn't see it before.
