### ISSUE TITLE
Change master to main, everywhere

### ISSUE THREAD

**Issue by wildsm** [Libensemble/libensemble#516]
See https://github.com/github/renaming

Some of this is coming automatically (https://github.com/github/renaming#later-this-year) 
but I wonder whether we want to be more proactive so as to catch all instances (Doc, contributing, etc.)

**Comment by jmlarson1** [comment]
We made consistent our usage of `is_master` to `is_manager` in #524

**Comment by jmlarson1** [comment]
Note that github says "Beginning in January 2021, we'll begin rolling out functionality to make it easier to rename the default branch of an existing repository:" 

Let's revisit this in February to see how easy it is.

**Comment by jmlarson1** [comment]
This looks easily enough by going to https://github.com/Libensemble/libensemble/branches and renaming `master` to `main`. Do you object @shuds13 ?

**Comment by jmlarson1** [comment]
This was resolved on May 4, 2021 after the release 0.7.2
