### ISSUE TITLE
Evaluate structure and duplication of alloc functions.

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#526]
I propose restructuring alloc functions to have more code-blocks made into alloc_support functions - eg. priority - support for cancelling sims so these features can be incorporated into different alloc functions.

First review existing alloc functions and key distinctions for different functions versus options to functions.

**Comment by shuds13** [comment]
@jmlarson1 

In merging in my CWP branch I will need to resolve conflicts in `start_only_persistent.py` - or create a different file/function. Mine has other features, but this is specifcally the 'async' return of value to the gen.

Some comparisons I've made between our solutions:

- gen_specs['user']['async'] v alloc_specs['user']['batch_mode']

I think there are different ways we can use these terms so may want to discuss terminology, but batch_mode has been used in a slightly different way before. However, I would think its an `alloc_specs` - though other things like `'given_back'` are listed as `alloc_specs['out']`. In reality, this works because H is mutable (essentially passed by reference), so is unlike sim/gen case. in the async/batch_mode it is an input. In other cases we have used `persis_info`. We should determine convention here.

- finding rows to return.

    returned_but_not_given = np.logical_and.reduce((H['returned'], ~H['given_back'], H['gen_worker'] == i)) 
    followed by
    inds_to_give = np.where(returned_but_not_given)[0]

    i have
    inds_since_last_gen = H['sim_id'][gen_inds][H['returned'] & ~H['given_back']]

I think yours is correct because these determine `H_rows`, which extract from H by index, not sim_id.
Do we have examples where sim_id is decoupled from index. Do we have tests for it?

- I have the `gen_work` line once, and logic to determine when it is called. I think probably a better way, as the line itself is the same.

Also, in the non-async case, I got rid of use of `H['gen_time']`, by simply only getting values that are not `'given_back'`. I think this is better?

Small note: I find `task_avail` a bit confusing - maybe work_avail?

**Comment by shuds13** [comment]
@jmlarson1 

Also just to note:

In this comparison:

    returned_but_not_given = np.logical_and.reduce((H['returned'], ~H['given_back'], H['gen_worker'] == i))
    followed by
    inds_to_give = np.where(returned_but_not_given)[0]

    i have
    inds_since_last_gen = H['sim_id'][gen_inds][H['returned'] & ~H['given_back']]

The second one (mine) is wrong - will not work if more than one gen, as it first filters on gen_inds and then trys to filter on whole array length. We should test this alloc func when more than one gen - and the close down on first persistent gen exit should probably be an option (or we use a calc_status return to trigger a shutdown).

Note that  my aim is to more towards something like the following...

https://github.com/Libensemble/libensemble/blob/feature/adaptive_workers_alloc_restructure/libensemble/alloc_funcs/start_only_persistent_using_wrapper.py

So this merge will be an intermediate solution.

I'm going to make a merger of our two functions and we can discuss on Thurs meeting, including naming of 'async' and whether to use gen_specs or alloc_specs, and whether there is any need for using gen_time here.

**Comment by shuds13** [comment]
gen_work/sim_work

- Should probably be functions that return Work
- For empty request range(len(H)) should probably be np.arange(len(H)) - if comes in as range - maybe convert in function

**Comment by jmlarson1** [comment]
Are you thinking      
`       gen_work(Work, i, gen_in, return_rows, persis_info.get(i))`
should be 
`      Work = gen_work(Work, i, gen_in, return_rows, persis_info.get(i))`
?

Which file's `range(len(H)) ` are you considering changing?

**Comment by shuds13** [comment]
I guess it would return ``Work[i]``. This is just a style choice really.

The range, it would be any that appear in the gen_work (or sim_work) line. As it expects a numpy array.
E.g.  

```python
       gen_work(Work, 1, gen_specs['in'], range(len(H)), persis_info.get(1),
                 persistent=True, active_recv=active_recv_gen)
```


I can certainly check for and fix this inside the function. I wanted to add this to the debugging also.


E.g. Fix in gen_work.
```python
    if isinstance(H_rows, range):
        H_rows = np.fromiter(H_rows, int)
```

Then to log:
```python
    logger.debug("Alloc func packing generator work request for worker {}. Packing sim_ids: {}".
                format(i, EnsembleDirectory.extract_H_ranges(Work[i]) or None))
```

**Comment by shuds13** [comment]
In #615 I have implemented the above in alloc_support to convert from any iterable type if possible:

```python

def check_H_rows(H_rows):
    """Ensure H_rows is a numpy array.  If it is not, then convert if possible,
    else raise an error.
   :returns: ndarray. H_rows
    """
    if isinstance(H_rows, np.ndarray):
        return H_rows
    try:
        H_rows = np.fromiter(H_rows, int)
    except Exception:
        raise AllocException("H_rows could not be converted to a numpy array. Type {}".
                             format(type(H_rows)))
    return H_rows
```

**Comment by shuds13** [comment]
Considering the alloc_support function: `avail_worker_ids(W, persistent=None, active_recv=False)`

Currently we have persistent=True/False supplied if we want to find only persistent workers or avoid persistent workers. Leaving a None returns any available worker. E.g. to get persistent workers only:

```python
    for i in avail_worker_ids(W, persistent=True)
```

But we need to be able to say I want a persistent sim or a persistent gen. As `W['persis_state']` already holds this, we can do an easy comparison in the function. I think it would be parsimonious to use the `persistent` argument to compare. So send e.g.

```python
    for i in avail_worker_ids(W, persistent=EVAL_GEN_TAG)
```

This can work, but a bit of a problem, if functions may already use True/False. As EVAL_SIM_TAG = 1 and EVAL_GEN_TAG = 2 (which seems wrong way round to me), then if they have persistent=True it would look for a persistent sim, which is the less common occurrence, and current examples all want to find a gen.

I cant think of a situation where they would want True to find any persistent worker (sim or gen). But I would rather True defaulted to gen.

In #615 I have changed all alloc function examples where `persistent=True` to `persistent=EVAL_GEN_TAG`. But there are still functions that have `persistent=False`, which works okay, but may prompt use of `persistent=True` leading to unexpected behaviour. An alternative would be a second argument to decide sim/gen (only relevant if persistent is True), but I dont like that.

**Comment by shuds13** [comment]
@jmlarson1 The suggestion from @jlnav is to make the default persistent=False instead of None, so that it would by default ask for non-persistent workers, and so generally a boolean value will not be used on call lines. I thinking this is probably the best answer. I doubt there is much use for 'None' which says just give me any worker.

**Comment by jmlarson1** [comment]
I like `persistent=False` and don't see any issue (or at least an issue that can't be fixed) by not having `None` as the default.

**Comment by shuds13** [comment]
Is there a likely use-case where you would want it to be None? I dont mind if my worker is persistent or not.

**Comment by jmlarson1** [comment]
As long as `False` and `None` have the same behavior, I think that's fine.

**Comment by jlnav** [comment]
Tentatively closing since #643 , containing the new ``AllocSupport`` class, was merged in.
