### ISSUE TITLE
Allow user to obtain a history and pass to libE (as H or H0)

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#530]
This is an idea for discussion.

Allow the user to initialize a history array straight from the history module, which can then be modified/initalized as they want and then passed to libE. This could mean adding an argument to libE to pass H. 

This could be useful if , for example, the user wan'ts to initialize history fields in a different way (e.g. initialise values to nan). It may also be useful with H0.

**Comment by jmlarson1** [comment]
I think its good for users to be able to define initialization values in `H` so they know what to expect in their user functions. It would seem like such functionality would replace the need for passing `H0`, right?
