### ISSUE TITLE
Support for Python 3.9

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#532]
We need to test libEnsemble with python3.9 and make any changes required.

**Comment by jmlarson1** [comment]
I'm starting to build the dependencies (there are no wheels). I'm scared of the petsc4py build...

**Comment by shuds13** [comment]
Conda now has python 3.9, but seems to not yet be supported on travis.

conda-forge packages have an auto-update PR made and I can get petsc4py at 3.9

**Comment by jmlarson1** [comment]
Still getting an error on 3.9: https://travis-ci.org/github/Libensemble/libensemble/builds/750261040

**Comment by jlnav** [comment]
Tests pass with 3.9 on GitHub actions: https://github.com/Libensemble/libensemble/actions/runs/461301242

**Comment by jlnav** [comment]
Tentatively closing by #563 , since Python 3.9 is being regularly tested on GitHub Actions
