### ISSUE TITLE
All values in H0 are marked given and returned.

### ISSUE THREAD

**Issue by jmlarson1** [Libensemble/libensemble#536]
This happens even if mark `H0['given'] = False` and `H0['returned'] = False` 

See lines 66 and 67 of `libensemble/libensemble/history.py`

So when we are giving a pregenerated sample (that has yet to be evaluated) I'm not sure if/how they are evaluated.

**Comment by shuds13** [comment]
I think they get evaluated because the alloc function does not check if points are given, it just assigns everything.

**Comment by jmlarson1** [comment]
Addressed by #537
