### ISSUE TITLE
Consider allowing add_unique_random_streams to not seed streams

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#542]
The random stream of each worker in add_unique_random_streams is seeded by the worker id. Perhaps we should allow passing a seed or None as an option. None would mean different streams are produced in each invocation.

**Comment by jmlarson1** [comment]
Let's allow user to pass a seed, and have the default be to take the worker's rank (if none given).
1. It helps with determinism in our regression tests
2. It will help users get "more deterministic" behavior (which is often expected)

**Comment by jlnav** [comment]
Closed by #545
