### ISSUE TITLE
repack_fields not always found in dir()

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#543]
I think globals() may work in place of dir().

@jmlarson1

**Comment by jmlarson1** [comment]
Is one preferred over the other? I thought `dir()` was an alias for `locals()` and would suffice for this use case.

I was trying to be as minimal as possible, but it doesn't matter. You must have an example where `_send_work_order` is invoked but the version check at the top of libE_manager is not invoked. 

I'll push a branch.

**Comment by shuds13** [comment]
On my laptop, at this point in the code I have.

dir is ['Work', 'self', 'w', 'work_rows']

locals is {'self': <libensemble.libE_manager.Manager object at 0x7f122f7efc50>, 'Work': {'H_fields': ['x', 'thetas', 'quantile'], 'persis_info': {'rand_stream': <mtrand.RandomState object at 0x7f122f7f11b0>, 'worker_num': 2}, 'tag': 1, 'libE_info': {'H_rows': array([0])}}, 'w': 2, 'work_rows': array([0])}

globals() is large and includes repack_fields().

It could be tested by doing a communcation and checking if the resulting data strucutre is a view (e.g. having the offsets attribute).
But I think globals() is pretty safe.

**Comment by jmlarson1** [comment]
See #544
