### ISSUE TITLE
Cori docs updates.

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#546]
Cori links have changed - need to update docs.

E.g. 
old: https://docs.nersc.gov/programming/high-level-environments/python/mpi4py/
new: https://docs.nersc.gov/development/languages/python/parallel-python/

and others.
Also the new lazy-mpi4py options maybe best to recommend for install, if it works.

Also add to FAQ (and maybe in Cori page).

*** Error in `***/bin/python': break adjusted to free malloc space: 0x0000010000000000 ***

This error has been encountered on Cori when running with mpi4py and implies incorrect installation of `mpi4py`. Please see the Cori instructions.

**Comment by jlnav** [comment]
Closed by #554
