### ISSUE TITLE
Error when trying to load past history

### ISSUE THREAD

**Issue by RemiLehe** [Libensemble/libensemble#550]
I recently observed an error when trying to load past history using the `H0` argument of the `libE` function.

I was able to reproduce the error with a modified version of the test `test_persistent_uniform_sampling.py`. Here is the modified file: 
[test_persistent_uniform_sampling.py](https://github.com/Libensemble/libensemble/files/5485048/test_persistent_uniform_sampling.py.txt)
The only modified lines are lines 52-59, which try to load a past `.npy` file, if there is one in the current folder:
```
import os
history_files = [filename for filename in os.listdir('.') if filename.endswith('.npy')]
if history_files == []:
    H0 = None
else:
    H0 = np.load(history_files[0])
H, persis_info, flag = libE(sim_specs, gen_specs, exit_criteria, persis_info,
                            alloc_specs, libE_specs, H0=H0)
```

I then ran this script twice:
```
python test_persistent_uniform_sampling.py --comm local --workers 3   # Produces a `.npy` history file
python test_persistent_uniform_sampling.py --comm local --workers 3   # Loads the history file, but raises an error
```
The second time, the script raises an error:
```
[0] libensemble.libE (ERROR): Manager exception raised .. aborting ensemble:
[0] libensemble.libE (ERROR): Dumping ensemble history with 40 sims evaluated:
Traceback (most recent call last):
  File "test_persistent_uniform_sampling.py", line 59, in <module>
    alloc_specs, libE_specs, H0=H0)
  File "/Users/rlehe/Documents/codes/libensemble/libensemble/libE.py", line 139, in libE
    persis_info, alloc_specs, libE_specs, H0)
  File "/Users/rlehe/Documents/codes/libensemble/libensemble/libE.py", line 335, in libE_local
    on_cleanup=cleanup)
  File "/Users/rlehe/Documents/codes/libensemble/libensemble/libE.py", line 155, in libE_manager
    exit_criteria, persis_info, wcomms)
  File "/Users/rlehe/Documents/codes/libensemble/libensemble/libE_manager.py", line 87, in manager_main
    result = mgr.run(persis_info)
  File "/Users/rlehe/Documents/codes/libensemble/libensemble/libE_manager.py", line 463, in run
    self._check_work_order(Work[w], w)
  File "/Users/rlehe/Documents/codes/libensemble/libensemble/libE_manager.py", line 250, in _check_work_order
    "but requested no fields to be sent.".format(work_rows, w)
AssertionError: Allocation function requested rows=range(0, 40) be sent to worker=1, but requested no fields to be sent.
```

**Comment by shuds13** [comment]
I think in this example, the alloc expects the persistent gen set up with no points coming back. I could get it to work by changing line 64 of start_only_persistent.py to:

    gen_work(Work, i, sim_specs['in'] + [n[0] for n in sim_specs['out']] + [('sim_id')], range(len(H)), persis_info[i], 

It wont pass the assert at the end as there are more generator iterations now in H - it will do 40 more.

I think in the first instance we should make sure your actual use-case works with H0. The persistent gen will need to support it.

Then I will aim to ensure the exiting alloc_funcs all support H0. I am currently reviewing the alloc_funcs to try to give more consistent support to existing features - this will include the variable size resources for workers.

**Comment by shuds13** [comment]
@RemiLehe 

I think a better fix than I suggested above is to keep the allocation function as it was and set your gen_specs['in'] in the calling script to:

    'in': ['sim_id', 'x', 'grad', 'f'],

As things stand, with persistent gens, gen_specs['in'] will be provided in H when the persistent gen is first called. It will need to include any fields that the gen will need to produce further points. When an H0 is not provided, this is often just empty, but the example test_persistent_aposmm_with_grad.py does use it. The gen will need to be written to use this this information.

Currently the alloc functions are deciding what is communicated back to the persistent gen, after it is running. This could be the same as initial fields, but it could be less - e.g. just the outputs from the sim, as the gen may already store 'x', for example. I think we should probably let the calling script decide these fields somehow, maybe with another gen field.

**Comment by RemiLehe** [comment]
Thanks for the advice, and sorry for the late reply! 
That fixed the issue!
