### ISSUE TITLE
Frequency with which we query alloc_f with persistent workers

### ISSUE THREAD

**Issue by jmlarson1** [Libensemble/libensemble#551]
Currently, we query the allocation function if any worker is not active. This is reasonable when all workers are non-persistent.

When workers are persistent, then we can query the allocation function with unnecessary frequency. Should the default be to only query the allocation function if there are idle nonpersistent workers?

**Comment by jmlarson1** [comment]
The only issue with repeated calls to the `alloc_f` is that it could "waste time" that could be spent listening to workers' responses. 

If made a change to only query `alloc_f` when there are idle, nonpersistent workers, then the `alloc_f` won't be able to issue `kill` signals to long-running workers (if desired).

**Comment by jlnav** [comment]
Interestingly enough, I think we've recently transitioned to calling the ``alloc_f`` _more_ often.

I _guess_ this is closed by #672 ? Please feel free to reopen if I'm wrong.
