### ISSUE TITLE
Missing dependencies in libE spack version

### ISSUE THREAD

**Issue by jmlarson1** [Libensemble/libensemble#553]
A user has reported the following: 

1. Your spack package is missing a dependency on `py-mpmath` otherwise I get an import error when I go to import APOSMM.
2. Your spack package (at least the stable version) refers to dfols by a name not provided by the package.  I guess they might have renamed it..

**Comment by jmlarson1** [comment]
@shuds13 Where do we update the spack dependencies? Should we just append/update 
`libensemble/docs/advanced_installation.rst` 
or is there somewhere else that such changes should be made?

**Comment by shuds13** [comment]
I think we should add more optional dependencies in the actual Spack package.py (which is in the Spack repo). I can do that. I see mpmath is in Spack so I can add. I guess we should have all the packages in the tests that are also in Spack as optional dependencies ('variants' in Spack).

**Comment by shuds13** [comment]
I have added mpmath and deap as optional dependencies in the Spack packages and opened a PR.

I have kept these optional and separate, so users can bring in just what they need.

The other optional/testsuite dependencies in setup.py were not in Spack

**Comment by shuds13** [comment]
The PR has been merged into Spack. I am also updating the docs in #554

@jmlarson1 
Maybe we should give dependencies for gen funcs at the top of the API page.

**Comment by jmlarson1** [comment]
@shuds13 I'm fine with adding them wherever you think is best. You aren't referring to this page, are you:

https://libensemble.readthedocs.io/en/latest/sim_gen_alloc_funcs.html#gen-f-api

**Comment by shuds13** [comment]
i meant [this page](https://libensemble.readthedocs.io/en/latest/examples/aposmm.html) and similar for others.

E.g. The rst something like:

Additional Dependencies
^^^^^^^^^^^^^^^^^^^^^^^

Required: mpmath_, SciPy_

Optional (see below): petsc4py_, nlopt_, DFO-LS_

**Comment by jmlarson1** [comment]
Yes, we should show the dependencies for each gen_f on its page.
