### ISSUE TITLE
Regression test: test_worker_exceptions.py 

### ISSUE THREAD

**Issue by jmlarson1** [Libensemble/libensemble#57]
Code run in test_worker_exceptions.py does not get included in code coverage. Is this because of the abort?

**Comment by shuds13** [comment]
I don't currently know of a way to get coverage when using mpi_abort as coverage.py will be terminated before its writes out the coverage data. However, I think for the test we should avoid the mpi_abort. Instead the issue then is two-fold.

1. The mpi_send (a blocking send to each worker in the manager finalize) with stop messag
2. A barrier in libE

I'm inclined to look at a way of getting round those sync points when workers get an exception. There are not any timeout options with the MPI though. Maybe somehow disable the sychronization if worker aborts are disabled.    

e.g. Make the send non-blocking, then a loop with mpi_test, with timeout, then if times out, cancel the send request and dont do the barrier.

Also maybe we can create some unit test that will run the exception code in serial.

**Comment by jmlarson1** [comment]
@shuds13 Can we close this Issue?

**Comment by shuds13** [comment]
We have covered this with unit testing and removed the regression tests. Closing.

**Comment by jmlarson1** [comment]
I'm moving this back to "to do" because we lost this test when we force manager to be rank 0.
