### ISSUE TITLE
Remove 'libE_' prefixes from core modules

### ISSUE THREAD

**Issue by jlnav** [Libensemble/libensemble#573]
Since modules are undeniably components of libEnsemble and aren't typically user-facing and at risk of being confused for other modules.

**Comment by jmlarson1** [comment]
This change has been made in #576. `logger` is possibly external facing... but I think the risk of confusion is near nothing. (There is an old package `logger` https://pypi.org/project/logger/ but the most common package is called `logging`.)

**Comment by jlnav** [comment]
> This change has been made in #576. `logger` is possibly external facing... but I think the risk of confusion is near nothing. (There is an old package `logger` https://pypi.org/project/logger/ but the most common package is called `logging`.)

Good point. On the off-chance a libE user is also using the other 'logger', it could be resolved with ``from libensemble import logger as libE_logger``.

A rename of the logger module would technically be a breaking API change then since we intend that part to be user facing. Thoughts on saving that rename for later or getting it over with now? I wouldn't mind either way.

**Comment by jmlarson1** [comment]
@shuds13 As the `logger` is API breaking, what do you think about making a branch for v0.8 that I can make the target of the PR #576 ?

**Comment by jmlarson1** [comment]
As the `logger` rename is API breaking, we can do it now in #608

**Comment by jlnav** [comment]
I believe this has been completely satisfied as of #608 .
