### ISSUE TITLE
Experiment with Windows on GitHub Actions

### ISSUE THREAD

**Issue by jlnav** [Libensemble/libensemble#574]

**Comment by jmlarson1** [comment]
@jlnav Should we close this for now?

**Comment by jlnav** [comment]
> @jlnav Should we close this for now?

I believe so. I'm relatively unfamiliar with how we'd install most of the non-Python packages on windows, and debugging this process might take lots of time for (I think) little benefit.

**Comment by shuds13** [comment]
@jlnav @jmlarson1 
But we could test Windows without the non-python packages. Make sure core libE works.

**Comment by jmlarson1** [comment]
Or, in other words, that @jlnav instituted extra tests, can we run the nonextra tests in Windows?

**Comment by jlnav** [comment]
7/27/22 - Log for investigating installing MPI on Windows:

- msmpi
   -  Installable from conda, but compilers not included
   -  no longer maintained, according to discussion on msmpi feedstock
   -  https://docs.microsoft.com/en-us/archive/blogs/windowshpc/how-to-compile-and-run-a-simple-ms-mpi-program
   - Trying path adjustment, compilation, and linking from above site

- mpi4py
   - no insight on compiling since mpi4py primarily concerned with MPI-Python interface

will be editing as I find more

**Comment by jlnav** [comment]
Closed by #869 !!!
