### ISSUE TITLE
libE_stats.txt should give sim_id for sim funcs instead of a count

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#587]
For sims, change Calc to sim_id.

- This should reflect the naming of output directories for sim_ids (should re-use code), and is more intuitive for users. 
- Will need to check postprocessing scripts still work.
- Gens can still use sequential numbers - also mirroring output directories.
- As before the output will be right aligned at width 5, but will expand if required.

**Comment by jlnav** [comment]
Tentatively closed by #588 ?
