### ISSUE TITLE
Clean up message tags and calc_status

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#63]
The use of tags in message_numbers.py, communications and separation from calc_status needs to be cleaned up. Calc status definitions should be moved to calc_info.py, (and eventually structured to make sense for multiple job sim funcs, and consider user defined statuses).

Definition of done:
For this task, clean up and decide on use of tags for comms and calc_status. Move definitions where appropriate and create future tasks as required.

**Comment by shuds13** [comment]
Calc_status will probably be moved to a field of the history array.

**Comment by jlnav** [comment]
Partially closed by #816 ???
