### ISSUE TITLE
Speed up job controller unit tests

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#68]
Job controller units tests take too long to run. Approx 20sec on laptop.

**Comment by shuds13** [comment]
Now running in about 4 seconds.

Old:
test_jobcontroller.py .................                                                                           [100%]
============================= 17 passed in 20.52 seconds

New:
test_jobcontroller.py .................                                                                           [100%]
============================= 17 passed in 3.95 seconds

The limitation is too ensure launched jobs run for long enough to get polled/killed as expected. This is probably about as short as we can safely make it.

Note: This gives 5 slowest jobs.
pytest --duration=5 test_jobcontroller.py

test_jobcontroller.py .................                                             [100%]
...
================================ slowest 5 test durations 
0.77s call     test_jobcontroller.py::test_launch_and_poll_multijobs
0.67s call     test_jobcontroller.py::test_kill_on_timeout
0.57s call     test_jobcontroller.py::test_launch_and_kill
0.34s call     test_jobcontroller.py::test_procs_and_machinefile_logic
0.32s call     test_jobcontroller.py::test_kill_on_file

**Comment by jmlarson1** [comment]
@shuds13  Is this not completing because of the speedup, or something else?

https://travis-ci.org/Libensemble/libensemble/jobs/419301163

**Comment by shuds13** [comment]
This is strange as job should have finished after about 0.2 seconds and clearly did not finish in 0.5 seconds. It works for me every time locally, I'll try with python2, though not sure what difference that will make, as the job itself is a binary.

**Comment by jmlarson1** [comment]
I restarted the 2.7 build and we'll see how it goes. Maybe Travis is/was slow.

**Comment by shuds13** [comment]
Closing this issue.
