### ISSUE TITLE
CI testing pure libensemble

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#703]
Add CI jobs to test only tests with minimal required dependencies for libEnsemble. This will just use local comms. 

These tests can include:
 - testing for windows
 - (temporailty) for python 3.10 or other cases where dependencies are not yet ready
 - Also for testing with openMPI (will only be relevant to tests using the executor)
 
No more dependencies should be installed than is necessary. This ensures, that minimal required dependencies remains sufficient; no tests pass due to something already installed.

**Comment by jlnav** [comment]
Presumably closed by #710
