### ISSUE TITLE
Discuss queue_update_function

### ISSUE THREAD

**Issue by jmlarson1** [Libensemble/libensemble#78]
Is this feature still needed? 
Should it be a stand-alone function?
We currently only have one example queue_update_function as a part of APOSMM. It provides the following functionality:

1. Preempts future residual calculations for a given point when a NaN is returned from any residual 
2. Preempts future residual calculations when a partial residual objective value is larger then a known upper bound on the optimum (only for sample points, not localopt points)

Both of these features could be incorporated in an allocation function. For the HFBTHO example, a student was able to send kills to running tasks when a NaN was found for any residual, and we should be able to incorporate this into libE. Should this be a part of the queue_update_function?

**Comment by jmlarson1** [comment]
We have decided to remove queue_update_functions and include such behavior in the alloc_funcs or gen_funcs.

**Comment by shuds13** [comment]
Removal effective version v0.4.1
