### ISSUE TITLE
SIGTERM at start of MPI launch

### ISSUE THREAD

**Issue by dbindel** [Libensemble/libensemble#80]
The JobController code to send signals was coded with a sleep(0.1) before signal sends; the comments claim that "without a small wait, the signals cannot work."  Removing the sleep causes problems in the test_doublekill unit test, at least in Travis (and intermittently on my local machine).  But I think the real problem might be that a SIGTERM sent to the MPI process group before the initialization completes can end up screwing things up in funny ways.  Details will depend on exactly how the MPI startup is handled, but the "wait and kill" protocol -- try SIGTERM, then send SIGKILL if things don't wrap up promptly enough -- should handle things gracefully.  There was a commented line in the test_doublekill unit test that set the wait and kill protocol with a timeout of 5 s, and uncommenting that line also seems to fix the issue.  On the other hand, the default protocol is wait-and-kill with a timeout of 60s, which is longer than the 20s timeout on the test.

I propose uncommenting the line in test_doublekill and getting rid of the timeout in the signaling code (and have done so in the branch I've been pushing forward).

**Comment by jlnav** [comment]
It's been a while, and we haven't experienced this issue recently. Closing, but feel free to reopen if necessary!
