### ISSUE TITLE
Unexpected slowdown with `safe_mode` being False and local comms.

### ISSUE THREAD

**Issue by jmlarson1** [Libensemble/libensemble#847]
Locally, when running
    python test_persistent_uniform_sampling.py --nworkers 5 --comms local
with the default `libE_specs['safe_mode'] = True`, I get the following utilization:
![gantt_safe](https://user-images.githubusercontent.com/10965637/171192739-e41f7518-fc49-40ff-a8a7-94faa8191c9a.png)

If I re-run with `libE_specs['safe_mode'] = False`, I get the following utilization
![gantt_not_safe](https://user-images.githubusercontent.com/10965637/171192751-73413b26-d75b-40ab-92a0-fd58e8250349.png)

Safe mode should make things only faster, not slower. Can someone else confirm this?

**Comment by shuds13** [comment]
@jmlarson1 Putting a small sleep in _alloc_work has same affect. ie. when safe_mode is False.

```python
    def _alloc_work(self, H, persis_info):
        """
        Calls work allocation function from alloc_specs. Copies protected libE
        fields before the alloc_f call and ensures they weren't modified
        """

        import time
        time.sleep(0.0001)
```

**Comment by jmlarson1** [comment]
So it would appear that the bug is somewhere else, right? 

Does `libE_specs["profile"] = True` help?

**Comment by jmlarson1** [comment]
The `w1` times are reporting when the manager tells `w1` to start doing gen work until the manager adds the generated points into the history. I'm going to open a branch with some debugging from the worker-side to see where the extra time is coming from.

**Comment by jmlarson1** [comment]
Plotting the timing from the worker side shows that it's taking the manager an unreasonable amount of time to send out the gen_work:
![gantt1](https://user-images.githubusercontent.com/10965637/171228123-0bd8fa60-5f9c-4a73-b6d1-0ff880de4272.png)

**Comment by shuds13** [comment]
We are hitting alloc many more times (i've not looked at time per call but I would expect a higher average when less spin calls), but from my timings it looks like the send back from manager to gen is taking the inordinate time.

**Comment by jmlarson1** [comment]
With just `safe_mode=False`, we can *speed things up* by adding a pause. By including 

        time.sleep(0.001)

in the `_alloc_work` call in the manager the utilization goes from:

**Comment by jmlarson1** [comment]
Revisiting, this is no longer an issue. Also, this can be due to the fact that these simulations are very fast.
