### ISSUE TITLE
Re-enable tests with broken dependencies

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#871]
- [x] test_persistent_gp.py - drgaonfly asscalar issue - Fixed but not yet in release. https://github.com/dragonfly/dragonfly/pull/94 - could pip install from github - or wait for PYPI release.

- [x] petsc tests. Conda install of petsc not working.
test_persistent_aposmm_tao_nm.py
test_persistent_aposmm_tao_blmvm.py
test_persistent_aposmm_pounders.py
Should be fixed - https://github.com/conda-forge/petsc-feedstock/issues/147

**Comment by shuds13** [comment]
Testing in PR #872

**Comment by jlnav** [comment]
Testing in PR #910

**Comment by jlnav** [comment]
Closed by #872 and #910
