### ISSUE TITLE
Make num_resource_sets the recommended way to use zero resource gen

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#882]
A specified zero resource worker is only necessary when a particular worker must be used (e.g. gen must run on worker 1). For most users this is not the case, so restructure docs to recommend the `num_resource_sets` _libE_specs_ option instead (and/or command line option `n_resource_sets`) instead of the `zero_resource_worker` option.

This can be used where sensible in examples, docs, tutorials, presentations. Some tests will still use zero_resource workers.

The `nsim_workers` command line option (_parse_args_) could also be changed to set this option - discuss?

`zero_resource_workers` will continue to be supported (where allocation functions support). This can also be extended.

**Comment by jlnav** [comment]
Closed by #905
