### ISSUE TITLE
Direct detection/use of GPUs per node

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#934]
Direct detection of GPUs and use to simply user workflows.

Eg. Could set things like CUDA_VISIBLE_DEVICES from slots automatically - along with other configuration criteria.

E.g. Perhaps allow users to specify `num_gpus` instead of `num_resource_sets` OR for something like the Wake-T/FBPIC example, where workers are much greater than available GPUs - manager can make N workers per group (node) GPU workers. Then `gen_specs["out"]` can specify something like `'use_gpus'  = True/False` alongside resource_sets. If True, they will schedule GPU resource sets.

This is likely to also tie in with platform settings (#927 ) as Summit, for example, cannot detect GPU count easily on compute nodes (though known info could be used in conjunction with platform detection - e.g. `hostname -d`)

**Comment by jlnav** [comment]
Closed by #983 , I believe
