### ISSUE TITLE
Intermittent failures

### ISSUE THREAD

**Issue by jmlarson1** [Libensemble/libensemble#960]
Rarely, we observe `Work` being received that is a numpy ndarray instead of a dictionary.

Given the relative infrequency of the error, we are looking to pull additional prints in `worker.py` 

https://github.com/Libensemble/libensemble/pull/959

Maybe we can consider asserting that `Work` is always a dictionary. We should revisit the changes to `worker.py` in #959 in the future.

**Comment by jlnav** [comment]
Has anyone observed this recently? I personally haven't, even on Actions.

**Comment by jmlarson1** [comment]
I have not either.
