### ISSUE TITLE
All attributes in `gen_specs` are passed to the workers as copies

### ISSUE THREAD

**Issue by AngelFP** [Libensemble/libensemble#975]
I currently have a workflow with a persistent generator where the actual generator object (for example, an Ax client) is passed to the `gen_f` as an attribute contained in the `gen_specs`. Then, inside the `gen_f`, this generator object is used to determine the new configurations to evaluate.

The problem is that after the run is completed, the original generator I created appears to be unchanged. See the (dummy) example below:

```python

# Create generator and add to `gen_specs`
ax_client = AxClient(...)
gen_specs['user']['ax_client'] = ax_client

# Run ensemble
libE(gen_specs, ...)

# Try to get information from generator
ax_client.get_best_trial()  # <- this will fail because ax_client is still empty of trials
``` 

This is because the `ax_client` that the `gen_f` was using was actually a copy of the one that was created in the calling script.

Is there any way of passing an object to the `gen_f` without it being a copy? It would be sufficient if this could be done with just one of the workers (i.e., with the worker taking care of running the persistent generator)

**Comment by shuds13** [comment]
As the workers are separate processors, rather than shared memory, this will be a copy. So it looks like we need to pass the object back to the manager. This could be done via `persis_info`. We will come up with an example.

**Comment by AngelFP** [comment]
Nice to hear! I had a look at the options that `multiprocessing` offers, mainly the [`Manager`](Executor.executor). They all seem to work well if the objects to pass are simple, but once they contain attributes that are instances of other complex objects it becomes really complicated (or simply not doable from my understanding). In the case of `optimas` we are on the second situation, so I didn't manage to get it working.

**Comment by jlnav** [comment]
I recently rediscovered solutions like ProxyStore (https://github.com/proxystore/proxystore), developed by other ANL folks, for passing Python objects over a network. This may be a possibility.

**Comment by jlnav** [comment]
I'm noting here that the same python objects are available to the worker processes when using threads as comms. But threads-workers can't operate in separate directories, so no sim_dirs. Plus this isn't actual parallelism on the libE side.

ProxyStore uses pickling, so that won't work for this case, I should've seen that earlier.

**Comment by shuds13** [comment]
@AngelFP Do you think #1216 (gen on manager) resolves this issue?

**Comment by AngelFP** [comment]
Yep, issue is solved.
